"""
══════════════════════════════════════════════════════════════
  DİL / LANGUAGE MODULE
  Tüm arayüz metinleri ve AI prompt çevirileri.
  Varsayılan: İngilizce (en)
══════════════════════════════════════════════════════════════
"""

CEVIRILER = {

    # ══════════════════════════════════════════
    #  ENGLISH (default)
    # ══════════════════════════════════════════
    "en": {
        # ── App ──
        "app_title":        "AI Terminal Assistant",
        "bar_title":        "  AI Terminal",

        # ── Status ──
        "ready":            "● Ready",
        "thinking":         "● Thinking...",

        # ── Memory ──
        "memory":           "Memory",

        # ── Title bar buttons ──
        "new_session":      "+ New Session",

        # ── Input ──
        "prompt_prefix":    "PS >",
        "placeholder":      "type your command...",

        # ── Welcome ──
        "welcome_title":    "AI Terminal Assistant v2.1",
        "welcome_model":    "Model: Qwen 2.5 3B · Context: {ctx} tokens",
        "welcome_db":       "Powered by: LingoCLI-AI Custom Finetuned Model",
        "welcome_memory":   "Memory: Token-based + auto-summarization (unlimited session)",
        "welcome_hint":     "Type your command and press Enter. Click ⓘ for help.\n",

        # ── Terminal output ──
        "running":          "  Running...",
        "success":          "  Success.",
        "cmd_error":        "  Command failed.",
        "cmd_not_generated":"  Command could not be generated.",
        "cancelled":        "  Cancelled.",
        "security_cancel":  "  Cancelled for security reasons.",
        "session_started":  "  New session started. All memory cleared.\n",
        "settings_saved":   "  Settings saved.",
        "lines_more":       "  ... ({n} more lines)",

        # ── Memory optimization ──
        "mem_optimizing":   "  ◆ Memory optimization: summarizing {n} messages...",
        "mem_done":         "  ◆ Done: {old}→{new} tokens (summary #{num})",

        # ── Danger ──
        "danger_prefix":    "  ⚠ DANGER:",
        "danger_title":     "DANGEROUS COMMAND",
        "danger_body":      "This command contains a dangerous operation!\n\nDanger: {d}\nCommand: {c}\n\nDo you really want to run it?",

        # ── Buttons (in terminal) ──
        "btn_run":          "[Run]",
        "btn_cancel":       "[Cancel]",

        # ── Errors ──
        "err_prefix":       "ERROR:",
        "err_connection":   "Connection error: Is LM Studio running on port 1234?",
        "err_timeout":      "Timeout: Model did not respond (60s).",
        "err_unexpected":   "Unexpected error:",

        # ── Settings window ──
        "settings_title":   "Settings",
        "settings_colors":  "Color Settings",
        "color_user":       "User text",
        "color_user_desc":  "Your typed commands",
        "color_cmd":        "AI command color",
        "color_cmd_desc":   "Commands generated by AI",
        "color_desc":       "Description color",
        "color_desc_desc":  "Command description text",
        "color_prompt":     "Prompt color",
        "color_prompt_desc":"PS > prompt color",
        "btn_save":         "Save",
        "btn_reset":        "Reset",
        "btn_cancel_set":   "Cancel",
        "lang_label":       "Language",
        "lang_desc":        "Interface & AI response language",

        # ── Info popup ──
        "info_title":       "Info",
        "info_memory":      "🧠 Memory Status",
        "info_bar":         "  [{bar}] {pct}%",
        "info_raw":         "  Raw messages: {n} pairs ({t} tokens)",
        "info_summary":     "  Summary:      {s} ({t} tokens)",
        "info_total":       "  Total:        {t} / {b} tokens",
        "info_remaining":   "  Remaining:    {r} tokens",
        "info_summaries":   "  Summarized:   {n} times",
        "info_total_msg":   "  Total messages: {n} (this session)",
        "info_budget_hdr":  "⚙️ Token Budget (Qwen 2.5 3B — {ctx} tokens)",
        "info_sys_budget":  "  System prompt: ~{n} tokens",
        "info_hist_budget": "  History budget: ~{n} tokens",
        "info_resp_budget": "  Response budget: ~{n} tokens",
        "info_safety":      "  Safety margin:  ~{n} tokens",
        "info_db_hdr":      "\n🛡️ Security Guardrails",
        "info_db_examples": "  Command examples: {n}",
        "info_db_cats":     "  Categories:       {n}",
        "info_db_danger":   "  Danger patterns:  {n}",
        "info_how_hdr":     "ℹ️ How It Works",
        "info_how_body":    "  When history exceeds the token budget, old messages\n  are automatically summarized. The last {n} message pairs\n  always stay raw. This allows unlimited sessions\n  — old context is never completely lost.",

        # ── Startup / Boot ──
        "boot_title":       "AI Terminal Assistant",
        "boot_checking":    "Checking LM Studio server...",
        "boot_found":       "LM Studio server found!",
        "boot_not_found":   "LM Studio server not found on port 1234.",
        "boot_launching":   "Launching LM Studio...",
        "boot_waiting":     "Waiting for server... ({s}s)",
        "boot_lms_not_installed": "LM Studio not found. Please install it.",
        "boot_ready":       "Server connected. Starting...",
        "boot_failed":      "Could not connect to LM Studio after {s}s.\nPlease start LM Studio manually and load a model.",
        "boot_manual":      "Start Manually",
        "boot_retry":       "Retry",
        "boot_quit":        "Quit",

        # ── Workspaces ──
        "ws_btn":           "📁 Projects",
        "ws_select":        "Select Project",
        "ws_new":           "[+] New Workspace",
        "ws_empty":         "  [Empty Slot]",
        "ws_clear_btn":     "🗑️ Clear",
        "ws_cleared":       "  Workspace cleared.",
        "ws_err_dir":       "  Cannot access directory: {d}",
        "ws_active":        "  Switched to workspace: {n}",
        "ws_default":       "  Switched to default workspace.",
        "ws_saving":        "  Saving workspace state...",
        "ws_mem_summary":   "  > Memory Summary: {s}",
        "info_ws_hdr":      "\n📁 Workspaces",
        "info_ws_active":   "  Active workspace: {n}",
        "info_ws_dir":      "  Directory: {d}",
        "info_ws_none":     "  No active workspace (default mode)",
        "info_ws_slots":    "  Slots used: {u}/3",
        "info_ws_how":      "  Each workspace stores its own memory. When you\n  switch projects, memory is frozen to disk and\n  restored when you return.",

        # ── AI prompt keywords ──
        "ai_desc_keyword":  "DESCRIPTION",
        "ai_cmd_keyword":   "COMMAND",
    },

    # ══════════════════════════════════════════
    #  TÜRKÇE
    # ══════════════════════════════════════════
    "tr": {
        # ── App ──
        "app_title":        "AI Terminal Asistanı",
        "bar_title":        "  AI Terminal",

        # ── Status ──
        "ready":            "● Hazır",
        "thinking":         "● Düşünüyor...",

        # ── Memory ──
        "memory":           "Hafıza",

        # ── Title bar buttons ──
        "new_session":      "+ Yeni Oturum",

        # ── Input ──
        "prompt_prefix":    "PS >",
        "placeholder":      "komutunuzu yazın...",

        # ── Welcome ──
        "welcome_title":    "AI Terminal Asistanı v2.1",
        "welcome_model":    "Model: Qwen 2.5 3B · Context: {ctx} token",
        "welcome_db":       "Guce Sahip: LingoCLI-AI (Özel Eğitilmiş) Model",
        "welcome_memory":   "Hafıza: Token tabanlı + otomatik özetleme (sınırsız oturum)",
        "welcome_hint":     "Komutunuzu yazıp Enter'a basın. Yardım için ⓘ butonuna tıklayın.\n",

        # ── Terminal output ──
        "running":          "  Çalıştırılıyor...",
        "success":          "  Başarılı.",
        "cmd_error":        "  Komut hata verdi.",
        "cmd_not_generated":"  Komut üretilemedi.",
        "cancelled":        "  İptal edildi.",
        "security_cancel":  "  Güvenlik nedeniyle iptal edildi.",
        "session_started":  "  Yeni oturum başlatıldı. Tüm hafıza sıfırlandı.\n",
        "settings_saved":   "  Ayarlar kaydedildi.",
        "lines_more":       "  ... ({n} satır daha)",

        # ── Memory optimization ──
        "mem_optimizing":   "  ◆ Hafıza optimizasyonu: {n} mesaj özetleniyor...",
        "mem_done":         "  ◆ Tamamlandı: {old}→{new} token (özet #{num})",

        # ── Danger ──
        "danger_prefix":    "  ⚠ TEHLİKE:",
        "danger_title":     "TEHLİKELİ KOMUT",
        "danger_body":      "Bu komut tehlikeli bir işlem içeriyor!\n\nTehlike: {d}\nKomut: {c}\n\nGerçekten çalıştırmak istiyor musunuz?",

        # ── Buttons (in terminal) ──
        "btn_run":          "[Çalıştır]",
        "btn_cancel":       "[İptal]",

        # ── Errors ──
        "err_prefix":       "HATA:",
        "err_connection":   "Bağlantı hatası: LM Studio açık ve 1234 portunda mı?",
        "err_timeout":      "Zaman aşımı: Model yanıt vermedi (60 sn).",
        "err_unexpected":   "Beklenmeyen hata:",

        # ── Settings window ──
        "settings_title":   "Ayarlar",
        "settings_colors":  "Renk Ayarları",
        "color_user":       "Kullanıcı metni",
        "color_user_desc":  "Sizin yazdığınız komutlar",
        "color_cmd":        "AI komut rengi",
        "color_cmd_desc":   "Yapay zekanın ürettiği komut",
        "color_desc":       "Açıklama rengi",
        "color_desc_desc":  "Komut açıklama metni",
        "color_prompt":     "Prompt rengi",
        "color_prompt_desc":"PS > yazısının rengi",
        "btn_save":         "Kaydet",
        "btn_reset":        "Sıfırla",
        "btn_cancel_set":   "İptal",
        "lang_label":       "Dil",
        "lang_desc":        "Arayüz ve AI yanıt dili",

        # ── Info popup ──
        "info_title":       "Bilgi",
        "info_memory":      "🧠 Hafıza Durumu",
        "info_bar":         "  [{bar}] %{pct}",
        "info_raw":         "  Ham mesaj:     {n} çift ({t} token)",
        "info_summary":     "  Özet:          {s} ({t} token)",
        "info_total":       "  Toplam:        {t} / {b} token",
        "info_remaining":   "  Kalan:         {r} token",
        "info_summaries":   "  Özetleme:      {n} kez yapıldı",
        "info_total_msg":   "  Toplam mesaj:  {n} (bu oturumda)",
        "info_budget_hdr":  "⚙️ Token Bütçesi (Qwen 2.5 3B — {ctx} token)",
        "info_sys_budget":  "  Sistem promptu: ~{n} token",
        "info_hist_budget": "  Geçmiş bütçe:   ~{n} token",
        "info_resp_budget": "  Yanıt bütçe:    ~{n} token",
        "info_safety":      "  Güvenlik marjı: ~{n} token",
        "info_db_hdr":      "\n🛡️ Güvenlik Kalkanı",
        "info_db_examples": "  Komut örnekleri: {n}",
        "info_db_cats":     "  Kategoriler:     {n}",
        "info_db_danger":   "  Güvenlik kalıbı: {n}",
        "info_how_hdr":     "ℹ️ Nasıl Çalışır",
        "info_how_body":    "  Geçmiş token bütçesini aştığında, eski mesajlar\n  otomatik olarak özetlenir. Son {n} mesaj çifti\n  her zaman ham kalır. Bu sayede sınırsız oturum\n  sürdürülebilir — eski bağlam asla tamamen kaybolmaz.",

        # ── Startup / Boot ──
        "boot_title":       "AI Terminal Asistanı",
        "boot_checking":    "LM Studio sunucusu kontrol ediliyor...",
        "boot_found":       "LM Studio sunucusu bulundu!",
        "boot_not_found":   "LM Studio sunucusu 1234 portunda bulunamadı.",
        "boot_launching":   "LM Studio başlatılıyor...",
        "boot_waiting":     "Sunucu bekleniyor... ({s}s)",
        "boot_lms_not_installed": "LM Studio bulunamadı. Lütfen yükleyin.",
        "boot_ready":       "Sunucu bağlandı. Başlatılıyor...",
        "boot_failed":      "LM Studio'ya {s}s içinde bağlanılamadı.\nLütfen LM Studio'yu manuel başlatın ve model yükleyin.",
        "boot_manual":      "Manuel Başlat",
        "boot_retry":       "Tekrar Dene",
        "boot_quit":        "Çıkış",

        # ── Workspaces ──
        "ws_btn":           "📁 Projeler",
        "ws_select":        "Proje Seç",
        "ws_new":           "[+] Yeni Çalışma Alanı",
        "ws_empty":         "  [Boş Slot]",
        "ws_clear_btn":     "🗑️ Temizle",
        "ws_cleared":       "  Çalışma alanı temizlendi.",
        "ws_err_dir":       "  Dizine erişilemiyor: {d}",
        "ws_active":        "  Çalışma alanına geçildi: {n}",
        "ws_default":       "  Varsayılan çalışma alanına geçildi.",
        "ws_saving":        "  Oturum state'i kaydediliyor...",
        "ws_mem_summary":   "  > Hafıza Özeti: {s}",
        "info_ws_hdr":      "\n📁 Çalışma Alanları",
        "info_ws_active":   "  Aktif çalışma alanı: {n}",
        "info_ws_dir":      "  Dizin: {d}",
        "info_ws_none":     "  Aktif çalışma alanı yok (varsayılan mod)",
        "info_ws_slots":    "  Kullanılan slot: {u}/3",
        "info_ws_how":      "  Her çalışma alanı kendi hafızasını saklar. Proje\n  değiştirdiğinizde hafıza diske dondurulur ve\n  geri döndüğünüzde otomatik yüklenir.",

        # ── AI prompt keywords ──
        "ai_desc_keyword":  "AÇIKLAMA",
        "ai_cmd_keyword":   "KOMUT",
    },
}


def t(dil: str, anahtar: str, **kwargs) -> str:
    """Çeviri fonksiyonu. Anahtar bulunamazsa İngilizce'den alır."""
    metin = CEVIRILER.get(dil, CEVIRILER["en"]).get(anahtar, "")
    if not metin:
        metin = CEVIRILER["en"].get(anahtar, f"[{anahtar}]")
    if kwargs:
        try:
            return metin.format(**kwargs)
        except (KeyError, IndexError):
            return metin
    return metin
